### ISSUE TITLE
Navodila, kje se dobi knjižnice

### ISSUE THREAD

**Issue by andrejbauer** [Migelo/SimulacijaPlanetov#5]
Zdi se, da je vajina koda odvisna od neke knjižnice `miglayout`. A bi lahko prosim dodala navodila, kje se to dobi, da bom lahko preizkusil vajin projekt.

**Comment by Migelo** [comment]
S commitom 150efffbf379882feaade5541e5ce3f3515e0f98 je knjižnica vključena po defaultu. Kot sem testiral, je potrebno še enkrat uvozit projekt v eclipse.

**Comment by andrejbauer** [comment]
Zakaj sploh uporabljata miglayout? Zdi se, da bi se mu lahko z lahkoto izognila, ker je tam samo za neko nepomembno nastavljanje pozicije gumbov, ki pa jo itak lahko naredita brez te knjižnice. (In v rensici gumbov sploh ne potrebujeta, ker lahko tiste tri zbire data v menu). Jaz ne bi navlekel zraven kar neke knjižnice zaradi ene vrstice kode.

**Comment by Migelo** [comment]
Sva uredila z 33fa5e3cf4fe21c7891637859e30abcee9d81d44.
Sedaj se prikaže samo sonce, to bova uredila naslednji teden, ko bova zaključila projekt.
